### ISSUE TITLE
[Question] How to convert pages in a PDF document to individual images?

### ISSUE THREAD

**Issue by dtom7** [J-F-Liu/lopdf#191]
Using this crate, is it possible to convert pages in a PDF document to individual images? Preferably PNG images.

**Comment by arifd** [comment]
Hi, I have very little experience with this crate so assume what I'm saying is wrong! But I think what you want is out of scope for `lopdf`, because it requires you to render the pdf PDF. If you want to create an image from a pdf, you probably want something like `pdftocairo` from https://poppler.freedesktop.org/

**Comment by frederikhors** [comment]
@J-F-Liu is this possible?

**Comment by J-F-Liu** [comment]
Rendering PDF to image is beyond the scope of this crate.

**Comment by frederikhors** [comment]
Thanks. I think we can close this issue now.
