### ISSUE TITLE
Add remove password protection?

### ISSUE THREAD

**Issue by luizfzs** [J-F-Liu/lopdf#52]
I had a quick look but couldn't find anything related to password protection. Does the library support it?

**Comment by J-F-Liu** [comment]
Not yet.

**Comment by jothan** [comment]
@J-F-Liu I am thinking of adding support for decrypting PDF files into lopdf.

Encryption seems tightly regulated where you are, will it be possible for you to merge such code in the main lopdf crate ? Otherwise, I can write a separate crate that can be made optional.

What is the best way to proceed ?

**Comment by J-F-Liu** [comment]
Merge requests are welcome.

**Comment by seanaye** [comment]
Are there any updates on this? Or any crates that can modify the permissions of pdfs? the `pdf` crate only deals with passwords on read-locked documents. I'm looking for crate that can remove write-locks on pdfs

**Comment by jwhear** [comment]
This is at least partially resolved by #228

**Comment by J-F-Liu** [comment]
Thanks
